version: "3.8"

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_USER: rainwater
      DB_PASSWORD: rainwater
      DB_NAME: rainwater
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rainwater
      POSTGRES_PASSWORD: rainwater
      POSTGRES_DB: rainwater
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
